weights: yolov5s.pt
cfg: ''
data: ./yolov5-master/data/wheat_head_data.yaml
hyp: ./yolov5-master/data/hyp.scratch.yaml
epochs: 10
batch_size: 2
img_size:
- 1024
- 1024
rect: false
resume: false
nosave: true
notest: false
noautoanchor: false
evolve: false
bucket: ''
cache_images: true
image_weights: false
device: ''
multi_scale: false
single_cls: false
adam: false
sync_bn: false
local_rank: -1
workers: 8
project: runs/train
entity: null
name: exp
exist_ok: false
quad: false
linear_lr: false
label_smoothing: 0.0
upload_dataset: false
bbox_interval: -1
save_period: -1
artifact_alias: latest
world_size: 1
global_rank: -1
save_dir: runs/train/exp
total_batch_size: 2
